title: "CLIrcuit"
theme: minima

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "AY2021S1-CS2113T-W13-3/tp"
github_icon: "diagrams/github-icon.png"

plugins:
  - jemoji
